platform :ios, '7.1'
pod 'AFNetworking', '~> 2.4.1'
pod 'MBProgressHUD', '~> 0.9'
#pod 'AMScrollingNavbar', '~> 1.3.2'
pod 'MLTransition', '~> 1.0'
pod 'XHRefreshControl', '~> 3.8'
pod 'BlocksKit', '~> 2.2.5'
pod 'Masonry', '~> 0.6.1'
